[project]
name = "django-tutorial-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.6",
    "django-debug-toolbar>=6.0.0",
    "pre-commit>=4.3.0",
]
